### ISSUE TITLE
Updating why section urls

### ISSUE THREAD

**Issue by ElectricEye89** [castuofa/dataarc-ui#46]
@nkos-eu 
For Concept scope note links, please use the "url" property of the concept data for those links. Note that some concepts do not have scope notes linked, so you may need to disable link if "url" is empty:
https://github.com/castuofa/dataarc-ui/blob/master/src/frontend/components/why-components/DartConceptDetails.vue#L84 

For "baseURI", please use prototype "this.$apiUrl", available immediately for all components.
https://github.com/castuofa/dataarc-ui/blob/master/src/mixins/DartCommon.js#L4

**Comment by CodeSpatial** [comment]
Closing this as #55 appears to have addressed this.
